pip install asyncio
pip install beautifulsoup4
pip install bs4
pip install captcha
pip install configparser
pip install ctx
pip install DateTime
pip install discord
pip install discord.py
pip install openpyxl
pip install pathtools
pip install psutil
pip install pylint
pip install pymongo
pip install requests
pip install setuptools
pip install soupsieve
pip install urllib3
pip install watchdog
pip install hgtk
pip install psycopg2
pip install pywebview
